### ISSUE TITLE
Embedded Data-Uri causes UnicodeDecodeError with CSS Compression

### ISSUE THREAD

**Issue by brian-montgomery** [jazzband/django-pipeline#242]
Whenever I try to embed an image (using the `'variant': 'data-uri'` option) and use CSS Compression (either the YuglifyCompressor or the CSSTidyCompressor), it fails with the following exception:

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 292: ordinal not in range(128)`

Taking out the variant option or removing the CSS Compressor fixes the issue.

The entire traceback is below:

```
Traceback (most recent call last):
  File "/Users/brianm/Projects/playground/djangular/env/lib/python2.7/site-packages/django/core/management/base.py", line 222, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/brianm/Projects/playground/djangular/env/lib/python2.7/site-packages/django/core/management/base.py", line 255, in execute
    output = self.handle(*args, **options)
  File "/Users/brianm/Projects/playground/djangular/env/lib/python2.7/site-packages/django/core/management/base.py", line 385, in handle
    return self.handle_noargs(**options)
  File "/Users/brianm/Projects/playground/djangular/env/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 164, in handle_noargs
    collected = self.collect()
  File "/Users/brianm/Projects/playground/djangular/env/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 120, in collect
    dry_run=self.dry_run)
  File "/Users/brianm/Projects/playground/djangular/env/lib/python2.7/site-packages/django_pipeline-1.3.11-py2.7.egg/pipeline/storage.py", line 28, in post_process
    packager.pack_stylesheets(package)
  File "/Users/brianm/Projects/playground/djangular/env/lib/python2.7/site-packages/django_pipeline-1.3.11-py2.7.egg/pipeline/packager.py", line 94, in pack_stylesheets
    variant=package.variant, **kwargs)
  File "/Users/brianm/Projects/playground/djangular/env/lib/python2.7/site-packages/django_pipeline-1.3.11-py2.7.egg/pipeline/packager.py", line 104, in pack
    content = compress(paths, **kwargs)
  File "/Users/brianm/Projects/playground/djangular/env/lib/python2.7/site-packages/django_pipeline-1.3.11-py2.7.egg/pipeline/compressors/__init__.py", line 78, in compress_css
    return self.with_data_uri(css)
  File "/Users/brianm/Projects/playground/djangular/env/lib/python2.7/site-packages/django_pipeline-1.3.11-py2.7.egg/pipeline/compressors/__init__.py", line 173, in with_data_uri
    return re.sub(URL_REPLACER, datauri, css)
  File "/Users/brianm/Projects/playground/djangular/env/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 292: ordinal not in range(128)
```

**Comment by samiro** [comment]
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

Work for me, with Python 2.7.
