### ISSUE TITLE
No file given for JS_Parse_Error

### ISSUE THREAD

**Issue by ktraff** [jazzband/django-pipeline#373]
There's a tiny syntax error in one of my javascript files, and unfortunately it's very difficult to find which file the error is coming from (kinda like a needle in a haystack!).

Here's the error I receive:

    python manage.py collectstatic

    You have requested to collect static files at the destination
    location as specified in your settings:

        /usr/share/nginx/www/static

    This will overwrite existing files!
    Are you sure you want to do this?

    Type 'yes' to continue, or 'no' to cancel: yes
    Traceback (most recent call last):
      File "manage.py", line 11, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
        output = self.handle(*args, **options)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 415, in handle
        return self.handle_noargs(**options)
      File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 173, in handle_noargs
        collected = self.collect()
      File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 117, in collect
        dry_run=self.dry_run)
      File "/usr/local/lib/python2.7/dist-packages/pipeline/storage.py", line 34, in post_process
        packager.pack_javascripts(package)
      File "/usr/local/lib/python2.7/dist-packages/pipeline/packager.py", line 110, in pack_javascripts
        return self.pack(package, self.compressor.compress_js, js_compressed, templates=package.templates, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pipeline/packager.py", line 104, in pack
        content = compress(paths, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pipeline/compressors/__init__.py", line 64, in compress_js
        js = getattr(compressor(verbose=self.verbose), 'compress_js')(js)
      File "/usr/local/lib/python2.7/dist-packages/pipeline/compressors/uglifyjs.py", line 12, in compress_js
        return self.execute_command(command, js)
      File "/usr/local/lib/python2.7/dist-packages/pipeline/compressors/__init__.py", line 236, in execute_command
        raise CompressorError(stderr)
    pipeline.exceptions.CompressorError: DEBUG: Error
        at new JS_Parse_Error (/usr/lib/nodejs/uglify-js/parse-js.js:260:22)
        at js_error (/usr/lib/nodejs/uglify-js/parse-js.js:268:15)
        at parse_error (/usr/lib/nodejs/uglify-js/parse-js.js:360:17)
        at Object.next_token [as input] (/usr/lib/nodejs/uglify-js/parse-js.js:602:17)
        at next (/usr/lib/nodejs/uglify-js/parse-js.js:706:37)
        at Object.semicolon [as 1] (/usr/lib/nodejs/uglify-js/parse-js.js:749:38)
        at prog1 (/usr/lib/nodejs/uglify-js/parse-js.js:1290:29)
        at simple_statement (/usr/lib/nodejs/uglify-js/parse-js.js:886:35)
        at /usr/lib/nodejs/uglify-js/parse-js.js:802:40
        at /usr/lib/nodejs/uglify-js/parse-js.js:1273:32
    DEBUG: { message: 'Unexpected character \'﻿\'',
      line: 3188,
      col: 1,
      pos: 151980,
      stack: 'Error\n    at new JS_Parse_Error (/usr/lib/nodejs/uglify-js/parse-js.js:260:22)\n    at js_error (/usr/lib/nodejs/uglify-js/parse-js.js:268:15)\n    at parse_error (/usr/lib/nodejs/uglify-js/parse-js.js:360:17)\n    at Object.next_token [as input] (/usr/lib/nodejs/uglify-js/parse-js.js:602:17)\n    at next (/usr/lib/nodejs/uglify-js/parse-js.js:706:37)\n    at Object.semicolon [as 1] (/usr/lib/nodejs/uglify-js/parse-js.js:749:38)\n    at prog1 (/usr/lib/nodejs/uglify-js/parse-js.js:1290:29)\n    at simple_statement (/usr/lib/nodejs/uglify-js/parse-js.js:886:35)\n    at /usr/lib/nodejs/uglify-js/parse-js.js:802:40\n    at /usr/lib/nodejs/uglify-js/parse-js.js:1273:32' }
    DEBUG: {"message":"Unexpected character '﻿'","line":3188,"col":1,"pos":151980,"stack":"Error\n    at new JS_Parse_Error (/usr/lib/nodejs/uglify-js/parse-js.js:260:22)\n    at js_error (/usr/lib/nodejs/uglify-js/parse-js.js:268:15)\n    at parse_error (/usr/lib/nodejs/uglify-js/parse-js.js:360:17)\n    at Object.next_token [as input] (/usr/lib/nodejs/uglify-js/parse-js.js:602:17)\n    at next (/usr/lib/nodejs/uglify-js/parse-js.js:706:37)\n    at Object.semicolon [as 1] (/usr/lib/nodejs/uglify-js/parse-js.js:749:38)\n    at prog1 (/usr/lib/nodejs/uglify-js/parse-js.js:1290:29)\n    at simple_statement (/usr/lib/nodejs/uglify-js/parse-js.js:886:35)\n    at /usr/lib/nodejs/uglify-js/parse-js.js:802:40\n    at /usr/lib/nodejs/uglify-js/parse-js.js:1273:32"}

Notice that file is nowhere specified, though I do get the line number and even the column and position.

**Comment by cyberdelia** [comment]
Compilers are now printing the whole file in case of error.
