### ISSUE TITLE
ImportError: No module named template while writing a DjangoTemplateJSCompiler 

### ISSUE THREAD

**Issue by groovecoder** [jazzband/django-pipeline#467]
I'm stuck trying to write a custom `DjangoTemplateJSCompiler` for `.djs` files so I can generate static `.js` files from Django templates.
When I try this:
```
  from django.template import render_to_string

  from pipeline.compilers import CompilerBase


  class DJSCompiler(CompilerBase):
      """ Simple compiler to render Django templates into JS files"""
      output_extension = 'js'

      def match_file(self, filename):
          return filename.endswith('.djs')

     def compile_file(self, infile, outfile, outdated=False, force=False):
          if not outdated and not force:
              return
         return render_to_string(infile, {}) 
```
I get:
```
(webalyzer)lcrouch-14912:webalyzer lcrouch$ ./manage.py collectstatic
/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/sorl/thumbnail/helpers.py:6: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module


You have requested to collect static files at the destination
location as specified in your settings:

    /Users/lcrouch/code/webalyzer/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
    collected = self.collect()
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    for original_path, processed_path, processed in processor:
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/pipeline/storage.py", line 26, in post_process
    packager.pack_stylesheets(package)
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/pipeline/packager.py", line 96, in pack_stylesheets
    variant=package.variant, **kwargs)
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/pipeline/packager.py", line 105, in pack
    paths = self.compile(package.paths, force=True)
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/pipeline/packager.py", line 99, in compile
    return self.compiler.compile(paths, force=force)
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/pipeline/compilers/__init__.py", line 56, in compile
    return list(executor.map(_compile, paths))
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/concurrent/futures/_base.py", line 579, in result_iterator
    yield future.result()
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/concurrent/futures/_base.py", line 396, in result
    return self.__get_result()
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/pipeline/compilers/__init__.py", line 32, in _compile
    for compiler in self.compilers:
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/pipeline/compilers/__init__.py", line 28, in compilers
    return [to_class(compiler) for compiler in settings.PIPELINE_COMPILERS]
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/pipeline/utils.py", line 23, in to_class
    module = importlib.import_module(module_path)
  File "/Users/lcrouch/python/webalyzer/lib/python2.7/site-packages/django/utils/importlib.py", line 45, in import_module
    __import__(name)
  File "/Users/lcrouch/code/webalyzer/webalyzer/base/compilers/django.py", line 3, in <module>
    from django.template import render_to_string
ImportError: No module named template
```
Is it because [the thread executing the compiler](https://github.com/cyberdelia/django-pipeline/blob/a12407e529e2b14f94deb139b9e1d7629f314a02/pipeline/compilers/__init__.py#L55-L56) doesn't have the same python execution environment?

**Comment by leonardoo** [comment]
This error is rare I think that could be the version of Django since changed as the templates were handled, could you tell me the version of Django you use?

**Comment by groovecoder** [comment]
Django 1.7.8

**Comment by cyberdelia** [comment]
This is an import error outside pipeline code, so there is nothing I can do.
Sorry.
