### ISSUE TITLE
wsgiref insists headers be strings, fails

### ISSUE THREAD

**Issue by chadmiller** [jazzband/django-pipeline#496]
I'm using dj_static as a wrapper to serve static files, Python3.4

```
[13/Sep/2015 13:49:46] "GET /s/css/site.a4b3a37942c0.css HTTP/1.1" 200 8629
Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "env/lib/python3.4/site-packages/dj_static.py", line 88, in __call__
    return self.cling(environ, start_response)
  File "env/lib/python3.4/site-packages/static/apps.py", line 125, in __call__
    start_response("200 OK", headers)
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 226, in start_response
    self.headers = self.headers_class(headers)
  File "/usr/lib/python3.4/wsgiref/headers.py", line 39, in __init__
    self._convert_string_type(v)
  File "/usr/lib/python3.4/wsgiref/headers.py", line 46, in _convert_string_type
    " of type str (got {0})".format(repr(value)))
AssertionError: Header names/values must be of type str (got b'text/javascript')
```

In the config, 'PIPELINE_MIMETYPES' contains tuples with byte arrays. If those are instead unicode strings, wsgiref is happy. Removing "b" before ' below seems to work. I don't know if it's *correct*.

```python
{
'PIPELINE_MIMETYPES': (
    (b'text/coffeescript', '.coffee'),
    (b'text/less', '.less'),
    (b'text/javascript', '.js'),
    (b'text/x-sass', '.sass'),
    (b'text/x-scss', '.scss')
),
}
```

**Comment by cyberdelia** [comment]
I would suggest using [whitenoise](https://pypi.python.org/pypi/whitenoise) here.
