### ISSUE TITLE
compressError in 1.6.1, works in 1.6.0

### ISSUE THREAD

**Issue by lucacorti** [jazzband/django-pipeline#523]
I'm on Django 1.9. With 1.6.0 everything works fine. With 1.6.1 collecstatic fails with:

```
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "venv/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "venv/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "venv/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 176, in handle
    collected = self.collect()
  File "venv/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 122, in collect
    for original_path, processed_path, processed in processor:
  File "venv/lib/python2.7/site-packages/pipeline/storage.py", line 26, in post_process
    packager.pack_stylesheets(package)
  File "venv/lib/python2.7/site-packages/pipeline/packager.py", line 96, in pack_stylesheets
    variant=package.variant, **kwargs)
  File "venv/lib/python2.7/site-packages/pipeline/packager.py", line 106, in pack
    content = compress(paths, **kwargs)
  File "venv/lib/python2.7/site-packages/pipeline/compressors/__init__.py", line 76, in compress_css
    css = getattr(compressor(verbose=self.verbose), 'compress_css')(css)
  File "venv/lib/python2.7/site-packages/pipeline/compressors/yuglify.py", line 16, in compress_css
    return self.compress_common(css, 'css', settings.YUGLIFY_CSS_ARGUMENTS)
  File "venv/lib/python2.7/site-packages/pipeline/compressors/yuglify.py", line 10, in compress_common
    return self.execute_command(command, content)
  File "venv/lib/python2.7/site-packages/pipeline/compressors/__init__.py", line 244, in execute_command
    raise CompressorError(stderr)
pipeline.exceptions.CompressorError: /bin/sh: -c: line 0: syntax error near unexpected token `--type=css'
/bin/sh: -c: line 0: `('node_modules/yuglify/bin/yuglify',) --type=css ('--terminal',)'
```

My pipeline settings are:

```
PIPELINE = {
    'DISABLE_WRAPPER': True,
    'JS_COMPRESSOR': 'pipeline.compressors.uglifyjs.UglifyJSCompressor',
    'UGLIFYJS_BINARY': os.path.join(BASE_DIR, 'node_modules/uglify-js/bin/uglifyjs'),
    'YUGLIFY_BINARY': os.path.join(BASE_DIR, 'node_modules/yuglify/bin/yuglify'),
    'TEMPLATE_EXT': '.hbs',
    'TEMPLATE_FUNC': 'Handlebars.compile',
    'TEMPLATE_NAMESPACE': 'Handlebars.templates',
    'STYLESHEETS': {...},
    'JAVASCRIPT': {...}
}
```

**Comment by cyberdelia** [comment]
Should be fixed in 1.6.3, sorry about that.

**Comment by lucacorti** [comment]
Nope, I have a different one with 1.6.3:

```
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "venv/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "venv/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "venv/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 176, in handle
    collected = self.collect()
  File "venv/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 122, in collect
    for original_path, processed_path, processed in processor:
  File "venv/lib/python2.7/site-packages/pipeline/storage.py", line 26, in post_process
    packager.pack_stylesheets(package)
  File "venv/lib/python2.7/site-packages/pipeline/packager.py", line 96, in pack_stylesheets
    variant=package.variant, **kwargs)
  File "venv/lib/python2.7/site-packages/pipeline/packager.py", line 106, in pack
    content = compress(paths, **kwargs)
  File "venv/lib/python2.7/site-packages/pipeline/compressors/__init__.py", line 78, in compress_css
    css = getattr(compressor(verbose=self.verbose), 'compress_css')(css)
  File "venv/lib/python2.7/site-packages/pipeline/compressors/yuglify.py", line 16, in compress_css
    return self.compress_common(css, 'css', settings.YUGLIFY_CSS_ARGUMENTS)
  File "venv/lib/python2.7/site-packages/pipeline/compressors/yuglify.py", line 10, in compress_common
    return self.execute_command(command, content)
  File "venv/lib/python2.7/site-packages/pipeline/compressors/__init__.py", line 252, in execute_command
    raise CompressorError(stderr)
pipeline.exceptions.CompressorError: ': -c: line 1: syntax error: unexpected end of file
```

**Comment by cyberdelia** [comment]
1.6.4 should do it, hopefully.
Happy new year!

**Comment by lucacorti** [comment]
Sure, fixed now. Happy new year to you!
