### ISSUE TITLE
please disable slimit test for Python >= 3

### ISSUE THREAD

**Issue by brianmay** [jazzband/django-pipeline#554]
Hello,

Can you please disable the slimit test for Python >= 3. slimit appears to be not Python 3 compatible and last release was in 2013.

As such, Debian is not going to be packaging python3-slimit any time soon.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=779321

This means the pipeline tests fail:

```
 ======================================================================
ERROR: test_slimit (tests.tests.test_compressor.CompressorImplementationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/tests/tests/test_compressor.py", line 230, in test_slimit
    'js', 'pipeline/compressors/slimit.js')
  File "/«PKGBUILDDIR»/tests/tests/test_compressor.py", line 215, in _test_compressor
    [_('pipeline/js/first.js'), _('pipeline/js/second.js')])
  File "/«PKGBUILDDIR»/pipeline/compressors/__init__.py", line 69, in compress_js
    js = getattr(compressor(verbose=self.verbose), 'compress_js')(js)
  File "/«PKGBUILDDIR»/pipeline/compressors/slimit.py", line 12, in compress_js
    from slimit import minify
ImportError: No module named 'slimit'

----------------------------------------------------------------------
Ran 89 tests in 0.832s

FAILED (errors=1, skipped=15)
```

**Comment by fdintino** [comment]
What you have encountered is actually a bug with the version of `ply` you have installed. The latest version of ply has that error [fixed](https://github.com/dabeaz/ply/commit/ee3bb4177786ea343c57208528cc4b5d0cf46918). As the travis tests show (and as you would find I suspect if you ran tox locally) slimit does indeed work with python 3.

**Comment by brianmay** [comment]
I am still getting at least one test failure with slimit on Python 3.5:

```
======================================================================
FAIL: test_case_1 (slimit.tests.test_lexer.LexerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/«PKGBUILDDIR»/.pybuild/pythonX.Y_3.5/build/slimit/tests/test_lexer.py", line 278, in test_func
    self.assertListEqual(result, expected)
  File "/«PKGBUILDDIR»/.pybuild/pythonX.Y_3.5/build/slimit/tests/test_lexer.py", line 55, in assertListEqual
    self.fail('Lists differ:\n' + message)
AssertionError: Lists differ:
- ['ID u03c0', 'ID u03c0_tail', 'VAR var', 'ID ua67c']
?                                ^^^    ^^^^^^^

+ ['ID \\u03c0', 'ID \\u03c0_tail', 'ID var\\ua67c']
?      ++            ++              ^^    ^^


----------------------------------------------------------------------
Ran 176 tests in 182.936s

FAILED (failures=1)
```

It is possible this has been fixed in the latest git version of slimit, however there have been no releases since 2013.

**Comment by fdintino** [comment]
There is a fork of slimit that has fixed that failing test case ([see here](https://github.com/lelit/slimit/commit/e8331659fb89e8a4613c5e4e338c877fead9c551)). As I see it, you have two options: you could include the patch for this unit test in your debian package (using quilt, perhaps) or you could include all of the changes in [lelit’s fork](https://github.com/lelit/slimit/) as patches to the upstream. Whatever you decide to do in preparing the debian package for slimit, I don't think it's all that relevant to this project. If the concern is that you want to build all the dependencies of pipeline for a debian package, you are welcome to omit slimit from that package since it is only an optional dependency. Use ``tox`` in the test phase of your debian package build to avoid having to create a debian package for slimit in order to run the unit test.

It is true that the slimit unit tests do not appear to be compatible with python 3. In particular they use the `ur"string"` for the failing test case you've pasted above. But slimit itself is indeed compatible with python 3, even if one of its unit tests is written in such a way that it fails in python 3. So I don't see a reason to disable slimit in this package for python 3.
