### ISSUE TITLE
AttributeError: 'Settings' object has no attribute 'PIPELINE'

### ISSUE THREAD

**Issue by manikos** [jazzband/django-pipeline#555]
Today I upgraded my project to django 1.9.4 and all of a sudden the following error occurred (during `manage.py check`):

```
Traceback (most recent call last):
  File "/usr/bin/pycharm-4.0.6/helpers/pycharm/django_manage.py", line 41, in <module>
    run_module(manage_file, None, '__main__', True)
  File "/usr/lib/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nick/django_projects/giteftra_shop/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/core/management/commands/check.py", line 51, in handle
    include_deployment_checks=include_deployment_checks,
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/admin_tools/checks.py", line 18, in check_admin_tools_configuration
    get_template('admin:admin/base.html')
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/template/loader.py", line 26, in get_template
    engines = _engine_list(using)
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/template/loader.py", line 143, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/template/utils.py", line 110, in all
    return [self[alias] for alias in self]
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/template/utils.py", line 101, in __getitem__
    engine = engine_cls(params)
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/template/backends/django.py", line 31, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/template/backends/django.py", line 49, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/template/backends/django.py", line 131, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/template/backends/django.py", line 144, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/pipeline/templatetags/pipeline.py", line 13, in <module>
    from ..collector import default_collector
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/pipeline/collector.py", line 11, in <module>
    from pipeline.finders import PipelineFinder
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/pipeline/finders.py", line 8, in <module>
    from pipeline.conf import settings
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/pipeline/conf.py", line 127, in <module>
    settings = PipelineSettings(_settings.PIPELINE)
  File "/home/nick/.virtualenvs/mosxou_env_19/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'PIPELINE'
```
I tried to debug it, without success. I (obviously) have `pipeline` in my `INSTALLED_APPS`. I tried it to move it along my `INSTALLED_APPS` (to the top, middle or last) without success again.

Any ideas? (Maybe is my fault?)

**Comment by manikos** [comment]
Why when I'm tired I submit issues?
I think I figured it out. It has something to do with PyCharm. I will see it again tomorrow morning. 
Sorry for any inconvenience.

**Comment by amites** [comment]
did you upgrade `django-pipeline` in the process?

`1.5`+ uses `PIPELINE`
`1.4` <= uses `PIPELINE_CSS`, `PIPELINE_JS`...

**Comment by manikos** [comment]
Forgot to mention that I used `django-pipeline 1.5` from the beginning, but seems like PyCharm has 2 ways of loading the package (from memory and from hard disk). Somehow, PyCharm used to load the package from memory (`django-pipeline 1.4`) and not from hard disk (`django-pipeline 1.5`). Thus, the error. Maybe this will help someone else. Very frustrating though!

Now its working, but my css/js files are not loaded in my .html file. But this is another topic. Will investigate it today.

Thanks for your time,
cheers from Greece
