### ISSUE TITLE
random test failures

### ISSUE THREAD

**Issue by brianmay** [jazzband/django-pipeline#622]
Hello,

I have got a report that this package fails tests randomly.

See http://bugs.debian.org/851722 for full details.

For example:

```
======================================================================
ERROR: test_pipeline_enabled_and_not_found (tests.tests.test_views.ServeStaticViewsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/django-pipeline-1.6.8/tests/tests/test_views.py", line 24, in setUp
    default_collector.clear()
  File "/build/django-pipeline-1.6.8/pipeline/collector.py", line 23, in clear
    dirs, files = self.storage.listdir(path)
  File "/usr/lib/python2.7/dist-packages/django/core/files/storage.py", line 399, in listdir
    for entry in os.listdir(path):
OSError: [Errno 2] No such file or directory: '/build/django-pipeline-1.6.8/tests/static'

----------------------------------------------------------------------
```

I have not been able to reproduce this myself. Wondering if maybe it is related to the tests being run in a different order or something.

Regards

**Comment by brianmay** [comment]
To reproduce:

```
git clean -fxd
PYTHONPATH=. /usr/bin/django-admin test -v3 --settings=tests.settings tests.tests.test_views.ServeStaticViewsTest
```

It seems that another test is required to run first to make the /build/django-pipeline-1.6.8/tests/static directory.

**Comment by brianmay** [comment]
Not only does that directory have to exist, it seems it needs to be populated with the required files too.
