### ISSUE TITLE
Unable to open file from default_storage after switching buckets.

### ISSUE THREAD

**Issue by Rugiewitz** [jazzband/django-pipeline#689]
```
from django.core.files.storage import default_storage
default_storage.bucket_name = 'other_bucket'
default_storage.exists('test_1.jpg')
 #Prints True
 default_storage.open('test_1.jpg','r')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/storages/backends/s3boto3.py", line 467, in _open
    raise IOError('File does not exist: %s' % name)
OSError: File does not exist: test_1.jpg
```

I'm not really too forsure why it think it doesn't exist after i was already able to confirm that it the file already exists there? Any idea why.

**Comment by Rugiewitz** [comment]
So i found my own solution for it.
Doing the Dir() of the object and going into other objects, a way to make it work is to 
default_storage._bucket._name = 'other_bucket' and this will fix the issue, guess when you're using the .open() functionality, it's using the bucket object's name to look for the file and NOT the default_storage bucket's name.
