### ISSUE TITLE
AttributeError: 'int' object has no attribute 'replace'

### ISSUE THREAD

**Issue by chrisspen** [jazzband/django-pipeline#703]
I'm using `STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage'` from django-pipeline==1.6.13 with Django==2.2.4, and it seems it somehow passing integers to staticfiles rendering methods, as I'm getting the exception:

Error: 'int' object has no attribute 'replace'

    TRACEBACK: Traceback (most recent call last):
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/core/handlers/base.py", line 143, in _get_response
        response = response.render()
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/response.py", line 106, in render
        self.content = self.rendered_content
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
        content = template.render(context, self._request)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
        return self.template.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 171, in render
        return self._render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
        return self.nodelist.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 937, in render
        bit = node.render_annotated(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
        return self.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
        return compiled_parent._render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
        return self.nodelist.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 937, in render
        bit = node.render_annotated(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
        return self.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
        return compiled_parent._render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
        return self.nodelist.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 937, in render
        bit = node.render_annotated(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
        return self.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
        return compiled_parent._render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
        return self.nodelist.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 937, in render
        bit = node.render_annotated(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
        return self.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
        return compiled_parent._render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
        return self.nodelist.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 937, in render
        bit = node.render_annotated(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
        return self.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
        result = block.nodelist.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 937, in render
        bit = node.render_annotated(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
        return self.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 987, in render
        output = self.filter_expression.resolve(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
        obj = self.var.resolve(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
        value = self._resolve_lookup(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
        current = current()
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/loader_tags.py", line 76, in super
        return mark_safe(self.render(self.context))
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
        result = block.nodelist.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 937, in render
        bit = node.render_annotated(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
        return self.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 987, in render
        output = self.filter_expression.resolve(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
        obj = self.var.resolve(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
        value = self._resolve_lookup(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
        current = current()
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/loader_tags.py", line 76, in super
        return mark_safe(self.render(self.context))
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
        result = block.nodelist.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 937, in render
        bit = node.render_annotated(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
        return self.render(context)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/pipeline/templatetags/pipeline.py", line 140, in render
        return self.render_compressed(package, package_name, 'css')
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/pipeline/templatetags/pipeline.py", line 69, in render_compressed
        package_type)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/pipeline/templatetags/pipeline.py", line 82, in render_compressed_output
        return method(package, package.output_filename)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/pipeline/templatetags/pipeline.py", line 147, in render_css
        'url': mark_safe(staticfiles_storage.url(path))
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 153, in url
        return self._url(self.stored_name, name, force)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/contrib/staticfiles/storage.py", line 134, in _url
        final_url = super().url(hashed_name)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/core/files/storage.py", line 331, in url
        url = filepath_to_uri(name)
      File "/usr/local/myproject/.env/lib/python3.7/site-packages/django/utils/encoding.py", line 252, in filepath_to_uri
        return quote(path.replace("\\", "/"), safe="/~!*()'")
    AttributeError: 'int' object has no attribute 'replace'

**Comment by broxeph** [comment]
May have to do with Memcached returning error codes in `HashedFilesMixin._stored_name()`. Would recommend switching to `ManifestStaticFilesStorage`, to avoid the external cache altogether, not to mention because `CachedStaticFilesStorage` is officially deprecated as of Django 2.2: https://docs.djangoproject.com/en/2.2/ref/contrib/staticfiles/#cachedstaticfilesstorage

Locally, this seems to work: `class PipelineManifestCachedStorage(PipelineMixin, ManifestStaticFilesStorage)`

**Comment by TheBuky** [comment]
#711 will resolve the problem

We need to wait for the new version published or you can clone repository. I will change the documentation, where: `PipelineManifestStorage` replace `PipelineCachedStorage`

**Comment by TheBuky** [comment]
Upgrade Django-pipeline to get the last version
